### ISSUE TITLE
Mal zum Lernen treffen?

### ISSUE THREAD

**Issue by jonasschneider** [phiresky/plangraph#2]
Hi, habe leider keine E-Mail-Adresse von dir gefunden ;-) Ein Kumpel von mir schreibt auch PlanGraph und würde sich gerne noch zusammensetzen. Wenn du magst, schreib mir doch eine mail an mail@jonasschneider.com.

**Comment by schuerg** [comment]
Wann habt ihr eure Prüfungstermine? Ich habe die Prüfung erst am 12.10.
Ab 22.09. hab ich Zeit zum lernen für PlanGraph und würde mich freuen, wenn ich mich dann mit euch austauschen könnte.

**Comment by phiresky** [comment]
Ja ich hab seine Facebook-Posts gesehn :D Ich hab mich allerdings schon mehrmals mit Leuten getroffen und bin deshalb in der Hinsicht schon gut versorgt.
